visualization:
  use_visdom: True
  visdom_port: 9000
  visdom_server: 'http://localhost'

  image:
    every: 10
    scale: 2

model:
  image_size: 224

dataset:
  images_path: '/home/alexey/programming/data-for-sha-hackaton/testThumbnails/'
  transformation_rectangle_size: 100
  transformation_deviate: 5
  shape: [224, 224]

train:
  lr: 0.001

  epochs: 50
  batch_size: 64
  number_of_processes: 8

  save:
    model: '../../data/weights/model1/'
    every: 2
  load: True